// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDit2syc3dR90npbOKaaS98VvureJCHlas',
    appId: '1:253525651364:web:9a9414307678c043ad1b31',
    messagingSenderId: '253525651364',
    projectId: 'grocery-2d446',
    authDomain: 'grocery-2d446.firebaseapp.com',
    storageBucket: 'grocery-2d446.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNhMIML5d8gxZ9rsdSldZswandxqTYtMw',
    appId: '1:253525651364:android:245233eab613a5daad1b31',
    messagingSenderId: '253525651364',
    projectId: 'grocery-2d446',
    storageBucket: 'grocery-2d446.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0-V7YSygBvy8LjM5c9d_Lqe0zavv9hlk',
    appId: '1:253525651364:ios:8439b6cf87dca1ddad1b31',
    messagingSenderId: '253525651364',
    projectId: 'grocery-2d446',
    storageBucket: 'grocery-2d446.appspot.com',
    iosBundleId: 'com.example.groceryapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0-V7YSygBvy8LjM5c9d_Lqe0zavv9hlk',
    appId: '1:253525651364:ios:8439b6cf87dca1ddad1b31',
    messagingSenderId: '253525651364',
    projectId: 'grocery-2d446',
    storageBucket: 'grocery-2d446.appspot.com',
    iosBundleId: 'com.example.groceryapp',
  );
}
